### PR TITLE
fix issue where non version tags failed

### PR DESCRIPTION
**Pull request by maleck13**
@alanmoran This should resolve the issue seen in staging. 
@laurafitzgerald @mikenairn ok to review

Verification

This is a bit tricky as we need a cluster with the older 3scale on it. Staging has this so perhaps @alanmoran  could rerun using the cli built from this branch against staging to show it now works as expected

### CODE REVIEW

**Comment by alanmoran** [comment]
@maleck13 Happy to verify this for you.  🎉 CVE's!  🎉

**master**
```
amoran at (╯°□°）╯︵ ┻━┻ in ~/go/src/github.com/integr8ly/heimdall/cmd/cli on master*
$ ./cli -namespaces=openshift-3scale
checking image : registry.redhat.io/3scale-amp2/apicast-gateway-rhel7:3scale2.7
checking image : registry.redhat.io/3scale-amp2/backend-rhel7:3scale2.7
checking image : registry.redhat.io/rhscl/redis-32-rhel7:3.2
checking image : registry.redhat.io/3scale-amp2/system-rhel7:3scale2.7
checking image : registry.redhat.io/3scale-amp2/memcached-rhel7:3scale2.7
checking image : registry.redhat.io/rhscl/mysql-57-rhel7:5.7
checking image : registry.redhat.io/3scale-amp2/zync-rhel7:3scale2.7
checking image : registry.redhat.io/rhscl/postgresql-10-rhel7
+--------------------+-----------------------------------+--------------+-----------+--------------------+----------------------+------------------+--------------+--------------------+-----------------------------+---------------+----------------+---------------+
| COMPONENT          | IMAGE                             | IMAGE STREAM | TAG       | UPTO DATE WITH TAG | PERSISTENT IMAGE TAG | LATEST PATCH TAG | FLOATING TAG | USING FLOATING TAG | UPTO DATE WITH FLOATING TAG | CRITICAL CVES | IMPORTANT CVES | MODERATE CVES |
+--------------------+-----------------------------------+--------------+-----------+--------------------+----------------------+------------------+--------------+--------------------+-----------------------------+---------------+----------------+---------------+
| apicast-production | 3scale-amp2/apicast-gateway-rhel7 | true         | 3scale2.7 | true               |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| apicast-staging    | 3scale-amp2/apicast-gateway-rhel7 | true         | 3scale2.7 | true               |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| backend-cron       | 3scale-amp2/backend-rhel7         | true         | 3scale2.7 | true               |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| backend-listener   | 3scale-amp2/backend-rhel7         | true         | 3scale2.7 | true               |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| backend-redis      | rhscl/redis-32-rhel7              | true         | 3.2       | true               | 3.2-47               | 3.2-47           | 3.2          | true               | true                        |             0 |              0 |             0 |
| backend-worker     | 3scale-amp2/backend-rhel7         | true         | 3scale2.7 | true               |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| system-app         | 3scale-amp2/system-rhel7          | true         | 3scale2.7 | false              |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| system-memcache    | 3scale-amp2/memcached-rhel7       | true         | 3scale2.7 | true               |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| system-mysql       | rhscl/mysql-57-rhel7              | true         | 5.7       | true               | 5.7-49               | 5.7-49           | 5.7          | true               | true                        |             0 |              0 |             0 |
| system-redis       | rhscl/redis-32-rhel7              | true         | 3.2       | true               | 3.2-47               | 3.2-47           | 3.2          | true               | true                        |             0 |              0 |             0 |
| system-sidekiq     | 3scale-amp2/system-rhel7          | true         | 3scale2.7 | false              |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| system-sphinx      | 3scale-amp2/system-rhel7          | true         | 3scale2.7 | false              |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| zync               | 3scale-amp2/zync-rhel7            | true         | 3scale2.7 | false              |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
| zync-database      | rhscl/postgresql-10-rhel7         | true         | latest    | true               | 1-46.1575996551      | 1-46.1575996551  | latest       | true               | true                        |             0 |              0 |             0 |
| zync-que           | 3scale-amp2/zync-rhel7            | true         | 3scale2.7 | false              |                      |                  | 3scale2.7    | true               | false                       |             0 |              0 |             0 |
+--------------------+-----------------------------------+--------------+-----------+--------------------+----------------------+------------------+--------------+--------------------+-----------------------------+---------------+----------------+---------------+
```

**INTLY-4976**
```
amoran at (╯°□°）╯︵ ┻━┻ in ~/go/src/github.com/integr8ly/heimdall/cmd/cli on (HEAD detached at origin/INTLY-4976)*
$ ./cli -namespaces=openshift-3scale
checking image : registry.redhat.io/3scale-amp2/apicast-gateway-rhel7:3scale2.7
checking image : registry.redhat.io/3scale-amp2/backend-rhel7:3scale2.7
checking image : registry.redhat.io/rhscl/redis-32-rhel7:3.2
skipping tag  latest  as it does not match on major minor patch version 3.2.*
checking image : registry.redhat.io/3scale-amp2/system-rhel7:3scale2.7
checking image : registry.redhat.io/3scale-amp2/memcached-rhel7:3scale2.7
checking image : registry.redhat.io/rhscl/mysql-57-rhel7:5.7
skipping tag  5.7  as it does not match on major minor patch version 5.7.*
skipping tag  latest  as it does not match on major minor patch version 5.7.*
checking image : registry.redhat.io/3scale-amp2/zync-rhel7:3scale2.7
checking image : registry.redhat.io/rhscl/postgresql-10-rhel7
+--------------------+-----------------------------------+------------------------------------------------------------------+--------------+-----------+--------------------+----------------------+--------------------+--------------+--------------------+-----------------------------+---------------+----------------+---------------+
| COMPONENT          | IMAGE                             | IMAGE HASH                                                       | IMAGE STREAM | TAG       | UPTO DATE WITH TAG | PERSISTENT IMAGE TAG | LATEST PATCH TAG   | FLOATING TAG | USING FLOATING TAG | UPTO DATE WITH FLOATING TAG | CRITICAL CVES | IMPORTANT CVES | MODERATE CVES |
+--------------------+-----------------------------------+------------------------------------------------------------------+--------------+-----------+--------------------+----------------------+--------------------+--------------+--------------------+-----------------------------+---------------+----------------+---------------+
| apicast-production | 3scale-amp2/apicast-gateway-rhel7 | 3f9becc79ad8b68b0d9b899278eee80fba960b835c7c777dd9190ca13cf072d7 | true         | 3scale2.7 | true               | 1.16                 | 1.16               | 3scale2.7    | true               | true                        |             0 |              0 |             0 |
| apicast-staging    | 3scale-amp2/apicast-gateway-rhel7 | 3f9becc79ad8b68b0d9b899278eee80fba960b835c7c777dd9190ca13cf072d7 | true         | 3scale2.7 | true               | 1.16                 | 1.16               | 3scale2.7    | true               | true                        |             0 |              0 |             0 |
| backend-cron       | 3scale-amp2/backend-rhel7         | 25b3659564917172753009859feba90eb6082ca5f1ee29cd5d4ed650d68035d2 | true         | 3scale2.7 | true               | 1.10                 | 1.10               | 3scale2.7    | true               | true                        |             0 |              0 |             0 |
| backend-listener   | 3scale-amp2/backend-rhel7         | 25b3659564917172753009859feba90eb6082ca5f1ee29cd5d4ed650d68035d2 | true         | 3scale2.7 | true               | 1.10                 | 1.10               | 3scale2.7    | true               | true                        |             0 |              0 |             0 |
| backend-redis      | rhscl/redis-32-rhel7              | a9bdf52384a222635efc0284db47d12fbde8c3d0fcb66517ba8eefad1d4e9dc9 | true         | 3.2       | true               | 3.2-47               | 3.2-47             | 3.2          | true               | true                        |             0 |              0 |             0 |
| backend-worker     | 3scale-amp2/backend-rhel7         | 25b3659564917172753009859feba90eb6082ca5f1ee29cd5d4ed650d68035d2 | true         | 3scale2.7 | true               | 1.10                 | 1.10               | 3scale2.7    | true               | true                        |             0 |              0 |             0 |
| system-app         | 3scale-amp2/system-rhel7          | 4f4bc1fcc3aad54d399715f7f18f0ef14467f91c1ce1ba00279062cad840d673 | true         | 3scale2.7 | false              | 1.11-27.1578407517   | 1.11-27.1579183773 | 3scale2.7    | true               | false                       |             0 |              1 |             0 |
| system-memcache    | 3scale-amp2/memcached-rhel7       | 2d89cb58699561e329e97de04a6df61f9d0ebf7b76b2a447b60bb16d22a820d9 | true         | 3scale2.7 | true               | 1.4.16               | 1.4.16             | 3scale2.7    | true               | true                        |             0 |              0 |             0 |
| system-mysql       | rhscl/mysql-57-rhel7              | 9a781abe7581cc141e14a7e404ec34125b3e89c008b14f4e7b41e094fd3049fe | true         | 5.7       | true               | 5.7-49               | 5.7-49             | 5.7          | true               | true                        |             0 |              0 |             0 |
| system-redis       | rhscl/redis-32-rhel7              | a9bdf52384a222635efc0284db47d12fbde8c3d0fcb66517ba8eefad1d4e9dc9 | true         | 3.2       | true               | 3.2-47               | 3.2-47             | 3.2          | true               | true                        |             0 |              0 |             0 |
| system-sidekiq     | 3scale-amp2/system-rhel7          | 4f4bc1fcc3aad54d399715f7f18f0ef14467f91c1ce1ba00279062cad840d673 | true         | 3scale2.7 | false              | 1.11-27.1578407517   | 1.11-27.1579183773 | 3scale2.7    | true               | false                       |             0 |              1 |             0 |
| system-sphinx      | 3scale-amp2/system-rhel7          | 4f4bc1fcc3aad54d399715f7f18f0ef14467f91c1ce1ba00279062cad840d673 | true         | 3scale2.7 | false              | 1.11-27.1578407517   | 1.11-27.1579183773 | 3scale2.7    | true               | false                       |             0 |              1 |             0 |
| zync               | 3scale-amp2/zync-rhel7            | bae5291e729c3e646b87e438b6bcf6d9de7eae914d819bf0d1ec7936877c6d16 | true         | 3scale2.7 | false              | 1.10-30.1575996901   | 1.10-30.1579183762 | 3scale2.7    | true               | false                       |             0 |              1 |             0 |
| zync-database      | rhscl/postgresql-10-rhel7         | 713619e271020556016c60fde6c623b356416d0bfd8bd4214e1b1315952ee8cd | true         | latest    | true               | 1-46.1575996551      | 1-46.1575996551    | latest       | true               | true                        |             0 |              0 |             0 |
| zync-que           | 3scale-amp2/zync-rhel7            | bae5291e729c3e646b87e438b6bcf6d9de7eae914d819bf0d1ec7936877c6d16 | true         | 3scale2.7 | false              | 1.10-30.1575996901   | 1.10-30.1579183762 | 3scale2.7    | true               | false                       |             0 |              1 |             0 |
+--------------------+-----------------------------------+------------------------------------------------------------------+--------------+-----------+--------------------+----------------------+--------------------+--------------+--------------------+-----------------------------+---------------+----------------+---------------+
```

**Comment by mikenairn** [comment]
This looks good to me, but I'm going to hold it until after this gets merged https://github.com/openshift/release/pull/6805

/hold

**Comment by maleck13** [comment]
Thanks @alanmoran

**Pull request merged**
