### PR TITLE
INTLY-4487

### PR DESCRIPTION
**Pull request by laurafitzgerald**
@maleck13 I've rebased on master and added some additional work on top of yours. I can squash the commits later but have kept them separate for now for ease of review.

Everything is building and running fine now. 

**Verifciation Steps**

`make cluster/prepare`
`make code/compile`
`make code/run` - this will take a while if your cache is cleaned
Applying an ImageMonitor works fine - at least no errors

You might need to clean your mod cache if you see any errors
`go clean -modcache GO111MODULE=ON` - this will take a while

_Monitoring_
Monitoring stuff can't be tested while running locally. I'm awaiting access to push an image to the integreatly org to test this. 

@mikenairn I've also bumped the version for the ci images and things seem to be building fine. I think there's a manual step to update that right? Happy to wait for further testing here before that tho.

### CODE REVIEW

**Comment by laurafitzgerald** [comment]
Some tests failing. Will revisit those tomorrow. /hold

**Comment by maleck13** [comment]
Are we expecting these jobs to pass?

**Comment by laurafitzgerald** [comment]
@maleck13 not just yet. The format one should be fixed now. I believe the image one will fail until we update the heimdall-base-image on ci. EDIT: or not. it's passed now.

**Comment by maleck13** [comment]
verified it still labels pods as expected 
/approve

**Pull request merged**
